name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - main
  tags:
    exclude:
      - '*'

variables:
  - group: GitSSHGroup
  - group: OctoDefault
  - name: MajorVersion
    value: 0
  - name: MinorVersion
    value: 1
  - name: BuildNumberShort
    value: '0.1.0'
    
stages:
  - stage: Build
    jobs:
      - job: linux
        displayName: helm build
        pool:
          name: Gerald-Local-Linux
        steps:
          - template: update-build-number.yml
          - checkout: self
            clean: true
            submodules: recursive
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: '$(SSHKnownHosts)'
              sshPublicKey: '$(SSHPublicKey)'
              sshPassphrase: '$(SSHPassphrase)'
              sshKeySecureFile: '$(SSHPrivateKeyFile)'     
          - task: HelmInstaller@1
            displayName: 'Install Helm'
            inputs:
              helmVersionToInstall: 'latest'
          - task: HelmDeploy@0
            displayName: 'helm package octo-mesh'
            inputs:
              command: package
              chartPath: '$(System.DefaultWorkingDirectory)/src/octo-mesh'
              chartVersion: '$(BuildNumberShort)'
              destination: '$(Build.artifactstagingdirectory)'
              arguments: '--app-version $(Build.BuildNumber)'
          - task: HelmDeploy@0
            displayName: 'helm package octo-mesh-adapter'
            inputs:
              command: package
              chartPath: '$(System.DefaultWorkingDirectory)/src/octo-mesh-adapter'
              chartVersion: '$(BuildNumberShort)'
              destination: '$(Build.artifactstagingdirectory)'
              arguments: '--app-version $(Build.BuildNumber)'
          - task: HelmDeploy@0
            displayName: 'helm package octo-mesh-app-template'
            inputs:
              command: package
              chartPath: '$(System.DefaultWorkingDirectory)/src/octo-mesh-app-template'
              chartVersion: '$(BuildNumberShort)'
              destination: '$(Build.artifactstagingdirectory)'
              arguments: '--app-version $(Build.BuildNumber)'
          - task: HelmDeploy@0
            displayName: 'helm package octo-mesh-crds'
            inputs:
              command: package
              chartPath: '$(System.DefaultWorkingDirectory)/src/octo-mesh-crds'
              chartVersion: '$(BuildNumberShort)'
              destination: '$(Build.artifactstagingdirectory)'
              arguments: '--app-version $(Build.BuildNumber)'
          - task: HelmDeploy@0
            displayName: 'helm package octo-mesh-communication-operator'
            inputs:
              command: package
              chartPath: '$(System.DefaultWorkingDirectory)/src/octo-mesh-communication-operator'
              chartVersion: '$(BuildNumberShort)'
              destination: '$(Build.artifactstagingdirectory)'
              arguments: '--app-version $(Build.BuildNumber) --dependency-update'
          - task: HelmDeploy@0
            displayName: 'helm package octo-mesh-schema-provider'
            inputs:
              command: package
              chartPath: '$(System.DefaultWorkingDirectory)/src/octo-mesh-schema-provider'
              chartVersion: '$(BuildNumberShort)'
              destination: '$(Build.artifactstagingdirectory)'
              arguments: '--app-version $(Build.BuildNumber) --dependency-update'
          - task: PowerShell@2
            displayName: 'Create version info file'
            inputs:
              targetType: 'inline'
              script: |
                New-Item $(build.artifactstagingdirectory)/versioninfo.txt
                Set-Content $(build.artifactstagingdirectory)/versioninfo.txt $(Build.BuildNumber)
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: local'
            inputs:
              ArtifactName: local
 

